### ISSUE TITLE
メニューからのRoutesを追加する

### ISSUE THREAD

**Issue by yamashita-kenngo** [autonomy-local/places-tenant#27]
# Task

## Description
メニューから各機能画面へのRoutesを構成する

## Acceptance Criteria
- [ ] path: reservation　申請管理に遷移する
- [ ] path: place　施設管理に遷移する
- [ ] path: group　団体管理に遷移する
- [ ] path: account　会計管理に遷移する
- [ ] path: rule　規約管理に遷移する
- [ ] path: meeting　運営会議に遷移する
- [ ] path: report　報告書作成に遷移する
- [ ] path: setting　設定に遷移する

## Tasks
```
メタタスクがあればリンク
```

- [] Routing設定をする
- [] 遷移先の各コンポーネント追加する

## Notes
```
memo
```
